In [2]:
from sklearn.datasets import load_boston
dataset = load_boston()
type(dataset)

sklearn.utils.Bunch

In [3]:
dir(dataset)

['DESCR', 'data', 'feature_names', 'filename', 'target']

In [4]:
x = dataset.data
y = dataset.target
print(x.shape, y.shape)

(506, 13) (506,)


In [7]:
type(x)

numpy.ndarray

In [19]:
import pandas as pd
df_X = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df_X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [43]:
df_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [44]:
df_X.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [22]:
from sklearn.model_selection import train_test_split

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

x_train, x_test, y_train, y_test = train_test_split(df, y, test_size=0.3, random_state=0)

In [23]:
from sklearn.linear_model import LinearRegression

clf = LinearRegression()　#classfication

In [24]:
clf.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
# パラメータwの確認 coefficient：係数
clf.coef_

array([-1.21310401e-01,  4.44664254e-02,  1.13416945e-02,  2.51124642e+00,
       -1.62312529e+01,  3.85906801e+00, -9.98516565e-03, -1.50026956e+00,
        2.42143466e-01, -1.10716124e-02, -1.01775264e+00,  6.81446545e-03,
       -4.86738066e-01])

In [26]:
# バイアスbの確認
clf.intercept_

37.93710774183255

In [27]:
# 決定係数R^2の確認
clf.score(x_train, y_train)

0.7645451026942549

In [28]:
# とりあえず一つのデータに対する予測を確認してみる
print(y_test[0])
clf.predict(x_test[:1])

22.6


array([24.9357079])

In [29]:
clf.score(x_test, y_test)

0.6733825506400194

### 改善を行う
前処理：今回は標準化を行う

In [30]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()

In [31]:
SS.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [32]:
SS.mean_

array([3.35828432e+00, 1.18093220e+01, 1.10787571e+01, 6.49717514e-02,
       5.56098305e-01, 6.30842655e+00, 6.89940678e+01, 3.76245876e+00,
       9.35310734e+00, 4.01782486e+02, 1.84734463e+01, 3.60601186e+02,
       1.24406497e+01])

In [33]:
SS.var_

array([6.95792305e+01, 5.57886665e+02, 4.87753572e+01, 6.07504229e-02,
       1.33257561e-02, 4.91423928e-01, 7.83932705e+02, 4.26314655e+00,
       7.49911344e+01, 2.90195600e+04, 4.93579208e+00, 7.31040807e+03,
       4.99634123e+01])

In [35]:
x_train_scaled = SS.transform(x_train)
x_test_scaled = SS.transform(x_test)

In [37]:
clf = LinearRegression()
clf.fit(x_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
clf.score(x_train_scaled, y_train)

0.7645451026942549

In [41]:
clf.score(x_test_scaled, y_test)

0.6733825506400195

標準化を行っても変化なしのため、べき変換に変更して予測

In [45]:
from sklearn.preprocessing import PowerTransformer

PT = PowerTransformer()
PT.fit(x_train)

x_train_scaled = PT.transform(x_train)
x_test_scaled = PT.transform(x_test)

clf = LinearRegression()
clf.fit(x_train_scaled, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
clf.score(x_train_scaled, y_train)

0.7859862562650238

In [47]:
clf.score(x_test_scaled, y_test)

0.7002856552456189

In [49]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('PT', PowerTransformer()),
    ('clf', LinearRegression() )
])

In [50]:
pipeline.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('PT',
                 PowerTransformer(copy=True, method='yeo-johnson',
                                  standardize=True)),
                ('LR',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [52]:
pipeline.score(x_train, y_train)

0.7859862562650238

In [53]:
result = pipeline.score(x_test, y_test)
result

0.7002856552456189